[project]
authors = [
    {name = "v.shuvalov", email = "mega.kefi36@gmail.com"}
]
name = "analgin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aio-pika>=9.5.5",
]
